# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('certificate_url', models.URLField(blank=True, default=None, null=True)),
                ('content', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Cubian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cubians/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Portoflio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portoflio/%Y/%m/%d/')),
                ('description', models.CharField(max_length=400)),
                ('mobile_url', models.URLField(blank=True, default=None, null=True)),
                ('cloud_url', models.URLField(blank=True, default=None, null=True)),
                ('web_url', models.URLField(blank=True, default=None, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'product'), (2, 'portoflio')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('description', models.CharField(max_length=400)),
                ('mobile_url', models.URLField(blank=True, default=None, null=True)),
                ('cloud_url', models.URLField(blank=True, default=None, null=True)),
                ('web_url', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='technologies/%Y/%m/%d/')),
                ('name', models.CharField(max_length=100)),
                ('subname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonianl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonianl/%Y/%m/%d/')),
                ('content', models.CharField(max_length=400)),
            ],
        ),
    ]
