# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubeMobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portoflio',
            old_name='cloud_url',
            new_name='android_url',
        ),
        migrations.RenameField(
            model_name='portoflio',
            old_name='mobile_url',
            new_name='ios_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cloud_url',
            new_name='android_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mobile_url',
            new_name='ios_url',
        ),
    ]
