# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeMobile', '0004_auto_20160821_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portoflio',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'mobile'), (2, 'cloud'), (3, 'website'), (4, 'desktop')]),
        ),
    ]
