# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubeMobile', '0005_auto_20160822_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubian',
            name='content',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
