# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubeMobile', '0008_auto_20160823_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
