# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubeMobile', '0009_delete_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content of post'),
        ),
    ]
