# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='CVs/%Y/%m/%d/')),
                ('phone_no', models.CharField(max_length=100)),
            ],
        ),
    ]
